In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("../Data/retail_sales_dataset.csv")

In [24]:
df.head()

,Fecha,Ciudad,Producto,Categoría,Cantidad,Precio Unitario,Descuento (%),Total Venta,Método Pago,Vendedor
0,2026-05-06,Pereira,Teclado,Accesorios,3,2190000,15,5584500.0,Daviplata,Andrés López
1,2026-04-13,Barranquilla,Disco SSD,Almacenamiento,2,3876000,0,7752000.0,Nequi,Sofía Martínez
2,2024-09-10,Cali,Monitor,Monitores,5,418000,15,1776500.0,Nequi,María Pérez
3,2024-09-29,Bucaramanga,Mouse,Accesorios,4,2369000,20,7580800.0,Nequi,Juan Rodríguez
4,2026-01-16,Medellín,Webcam,Video,1,3379000,0,3379000.0,Transferencia,María Pérez

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            8000 non-null   str
 1   Ciudad           8000 non-null   str
 2   Producto         8000 non-null   str
 3   Categoría        8000 non-null   str
 4   Cantidad         8000 non-null   int64
 5   Precio Unitario  8000 non-null   int64
 6   Descuento (%)    8000 non-null   int64
 7   Total Venta      8000 non-null   float64
 8   Método Pago      8000 non-null   str
 9   Vendedor         8000 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 625.1 KB

In [26]:
df.describe()

          Cantidad  Precio Unitario  Descuento (%)   Total Venta
count  8000.000000     8.000000e+03    8000.000000  8.000000e+03
mean      3.001375     2.031314e+06      10.017500  5.478219e+06
std       1.401827     1.140211e+06       7.066625  4.264486e+06
min       1.000000     4.000000e+04       0.000000  3.600000e+04
25%       2.000000     1.056000e+06       5.000000  2.061525e+06
50%       3.000000     2.046000e+06      10.000000  4.405625e+06
75%       4.000000     2.997500e+06      15.000000  8.004600e+06
max       5.000000     4.000000e+06      20.000000  1.998500e+07

In [27]:
df.isnull().sum()

Fecha              0
Ciudad             0
Producto           0
Categoría          0
Cantidad           0
Precio Unitario    0
Descuento (%)      0
Total Venta        0
Método Pago        0
Vendedor           0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.sample(10)

,Fecha,Ciudad,Producto,Categoría,Cantidad,Precio Unitario,Descuento (%),Total Venta,Método Pago,Vendedor
4657,2025-08-26,Medellín,Webcam,Video,5,3680000,0,18400000.0,Transferencia,Juan Rodríguez
1812,2025-03-06,Cali,Laptop,Computadores,5,2708000,15,11509000.0,Daviplata,María Pérez
4178,2025-12-16,Bucaramanga,Monitor,Monitores,1,2046000,15,1739100.0,Tarjeta,Juan Rodríguez
3763,2025-07-10,Barranquilla,Memoria RAM,Componentes,2,1334000,0,2668000.0,Daviplata,María Pérez
2133,2024-08-12,Cali,Laptop,Computadores,1,1223000,0,1223000.0,Nequi,María Pérez
783,2025-05-20,Barranquilla,Mouse,Accesorios,5,1905000,15,8096250.0,Efectivo,Andrés López
1533,2025-03-24,Pereira,Teclado,Accesorios,2,2184000,15,3712800.0,Transferencia,Carlos Gómez
2275,2024-09-24,Santa Marta,Impresora,Oficina,5,1867000,10,8401500.0,Tarjeta,Sofía Martínez
3714,2025-05-07,Santa Marta,Silla Gamer,Muebles,3,2167000,15,5525850.0,Tarjeta,Andrés López
6254,2025-02-21,Bucaramanga,Silla Gamer,Muebles,3,2708000,0,8124000.0,Nequi,Carlos Gómez

In [30]:
len(df) # Cuantas ventas existen?

8000

In [31]:
df.shape

(8000, 10)

In [32]:
df["Total Venta"].sum() # Cuánto dinero generó la empresa?

np.float64(43825750400.0)

In [33]:
df["Total Venta"].mean() # Cuál fue la venta promedio?

np.float64(5478218.8)

In [34]:
df["Total Venta"].max() # La venta más alta

np.float64(19985000.0)

In [35]:
df["Total Venta"].min() # La venta más baja

np.float64(36000.0)

In [36]:
df["Producto"].value_counts() # El producto más vendido

Producto
Laptop         821
Impresora      815
Teclado        814
Monitor        806
Disco SSD      804
Audífonos      800
Memoria RAM    798
Silla Gamer    785
Webcam         780
Mouse          777
Name: count, dtype: int64

In [37]:
df["Categoría"].value_counts() # Cuál categoría vende más?

Categoría
Accesorios        1591
Computadores       821
Oficina            815
Monitores          806
Almacenamiento     804
Audio              800
Componentes        798
Muebles            785
Video              780
Name: count, dtype: int64

In [38]:
df.groupby("Ciudad")["Total Venta"].sum() # En cuál ciudad se vende más?

Ciudad
Barranquilla    5.452800e+09
Bogotá          5.125026e+09
Bucaramanga     5.505021e+09
Cali            5.738068e+09
Cartagena       5.634886e+09
Medellín        5.656080e+09
Pereira         5.451435e+09
Santa Marta     5.262434e+09
Name: Total Venta, dtype: float64

In [39]:
list(df.columns)

['Fecha',
 'Ciudad',
 'Producto',
 'Categoría',
 'Cantidad',
 'Precio Unitario',
 'Descuento (%)',
 'Total Venta',
 'Método Pago',
 'Vendedor']

In [40]:
df.groupby("Vendedor")["Total Venta"].sum()

Vendedor
Andrés López      7.027951e+09
Carlos Gómez      7.394473e+09
Juan Rodríguez    7.516617e+09
Laura Sánchez     6.972717e+09
María Pérez       7.265932e+09
Sofía Martínez    7.648062e+09
Name: Total Venta, dtype: float64

In [41]:
df["Método Pago"].value_counts()

Método Pago
Efectivo         1667
Transferencia    1614
Nequi            1597
Tarjeta          1583
Daviplata        1539
Name: count, dtype: int64

In [42]:
df.groupby("Método Pago")["Total Venta"].sum()

Método Pago
Daviplata        8.511360e+09
Efectivo         9.063989e+09
Nequi            8.680481e+09
Tarjeta          8.772566e+09
Transferencia    8.797355e+09
Name: Total Venta, dtype: float64

In [43]:
df.groupby("Producto")["Total Venta"].sum().sort_values(ascending=False).head()

Producto
Teclado        4.507538e+09
Monitor        4.493703e+09
Disco SSD      4.426109e+09
Silla Gamer    4.423209e+09
Audífonos      4.416334e+09
Name: Total Venta, dtype: float64

In [44]:
df["Fecha"] = pd.to_datetime(df["Fecha"])
df["Mes"] = df["Fecha"].dt.month_name()
df.groupby("Mes")["Total Venta"].sum()

Mes
April        3.528589e+09
August       3.412317e+09
December     3.818947e+09
February     3.291851e+09
January      3.837693e+09
July         3.745984e+09
June         3.708378e+09
March        3.685436e+09
May          3.667870e+09
November     3.426917e+09
October      3.917443e+09
September    3.784326e+09
Name: Total Venta, dtype: float64

In [45]:
df.groupby("Categoría")["Total Venta"].mean()

Categoría
Accesorios        5.530275e+06
Almacenamiento    5.505111e+06
Audio             5.520418e+06
Componentes       5.493676e+06
Computadores      5.332648e+06
Monitores         5.575314e+06
Muebles           5.634661e+06
Oficina           5.354407e+06
Video             5.310036e+06
Name: Total Venta, dtype: float64

In [46]:
df.groupby("Vendedor")["Total Venta"].mean()

Vendedor
Andrés López      5.280203e+06
Carlos Gómez      5.584950e+06
Juan Rodríguez    5.535064e+06
Laura Sánchez     5.434697e+06
María Pérez       5.492012e+06
Sofía Martínez    5.538061e+06
Name: Total Venta, dtype: float64